---
output:
  html_document:
    toc: yes
    toc_depth: 3
    toc_float: yes
---
### R installation

+ Open an internet browser and go to www.r-project.org.

+ Click the "download R" link in the middle of the page under "Getting Started."

+ Select a CRAN location (a mirror site) and click the corresponding link.

+ Click on the "Download R for (Mac) OS X" link at the top of the page.

+ Click on the file containing the latest version of R under "Files."

+ Save the .pkg file, double-click it to open, and follow the installation instructions.

+ Now that R is installed, you need to download and install RStudio.

### RStudio installation

+ Go to www.rstudio.com and click on the "Download RStudio" button.

+ Click on "Download RStudio Desktop."

+ Click on the version recommended for your system, or the latest Mac version, save the .dmg file on your computer, double-click it to open, and then drag and drop it to your applications folder.

### RStudio and R
Is a developer environment for coding, data management, and version control.  

Multi-pane structure

+ Script editor  

+ Console

+ Environment and history

+ Files, plots, packages and help

### Projects in Rstudio

https://swcarpentry.github.io/r-novice-gapminder/02-project-intro/

### Script Editor
Allows the user to create multi-line code. It is here that you will develop your code and send it to the console. You will save your scripts as appropriately titled .r files.

To create a new R script you can either go to File -> New -> R Script, or click on the icon with the "+" sign and select "R Script", or simply press Ctrl+Shift+N. Make sure to save the script.

### Console
The console is where you can type commands and see output.

`>` is the R Prompt Symbol:
You should see the R prompt symbol in your console. If you don't see the prompt, you cannot execute code.

`+` is the R Prompt Symbol meaning you have unfinished code from the previous line. This often occurs if you have an open (unmatched) parentheses or a multiline input.  

Pressing the `ESC` will return the `>` symbol to your console.

### Files tab
The files tab shows the directory structure and allows GUI manipulation of directories.

### Plots tab
The plots tab will show all your figures and it is possible to scroll through multiple plots windows.

### Packages tab
Provides a list of installed packages and a mechanism to load new ones. Here, you can install packages here or using the command line (in the console).

```{r, eval = F}
# In the console type:
install.packages("package name in quotes")
# Example:
install.packages("dplyr")
```

For some packages you will see that "dependencies" are installed when the desired package is installed. These are the packages that the installed package needs in order to run some or all of the functions.

### Help tab

This tab will be automatically selected whenever you run help code in the Console.

### History tab
The history tab keeps a record of all previous commands. This can be useful when testing and running processes. To use archived code here, select all and click on the "To Source" icon, a window on the left will open with the list of commands. 

### Environment tab
Displays data, their classes, and dimensions in your workspace.

### Installing R packages

https://www.r-bloggers.com/installing-r-packages/

### Change my Rprofile site

Every time R starts a number of things happen. It can be useful to understand this startup process, so you can make R work the way you want it, fast. This link explains how.

https://csgillespie.github.io/efficientR/r-startup.html